#!/bin/bash
# Set up legacyhalos code

echo "Loading legacyhalos environment"

unset PYTHONPATH # clear PYTHONPATH

export LEGACYHALOS_DIR=$IM_WORK_DIR/projects/legacyhalos
export LEGACYHALOS_CODE_DIR=$HOME/legacyhalos

export PYTHONPATH=$LEGACYHALOS_CODE_DIR/py:$PYTHONPATH
export PATH=$LEGACYHALOS_CODE_DIR/bin:$PATH

conda activate legacyhalos
